language: python
services:
  - docker
python:
  - "2.7"
install:
  - make deps
script:
  - make test
  - make docker_build
  - make docker_push
depoly:
  provider: heroku
  app: guarded-springs-54478
  api_key: ${HEROKU_API_KEY}
